### ISSUE TITLE
How to use this ?

### ISSUE THREAD

**Issue by minhnq1618** [durkinza/CTFd_Split_Scoreboard#1]
Hello, if i want to use this then what is the name of the directory should i store the code in CTFd/plugins for my CTFd to understand it ?

**Comment by durkinza** [comment]
The directory name should match the repo name (`CTFd/plugins/CTFd_Split_Scoreboard`).
This is due to a few files pulling custom js and css files specific to this plugin using it's full directory path.

If you're installing the plugin with a git pull, then the directory name will match the repo name by default.

It is possible to use a different directory name if you are willing to edit a few files in the plugin. 
https://github.com/durkinza/CTFd_Split_Scoreboard/search?q=CTFd_Split_Scoreboard
Updating the lines in the files from that search will allow you to use a different directory name.

**Comment by minhnq1618** [comment]
Thank you, when i tried to use this project with CTFd version 3.2.1, it gave me this error : 
```
ctfd_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
ctfd_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "manage.py", line 14, in <module>
ctfd_1   |     app = create_app()
ctfd_1   |   File "/opt/CTFd/CTFd/__init__.py", line 281, in create_app
ctfd_1   |     init_plugins(app)
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/__init__.py", line 196, in init_plugins
ctfd_1   |     module.load(app)
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/CTFd_Split_Scoreboard/__init__.py", line 17, in load
ctfd_1   |     override_template('split_scoreboard_attr.html', open(os.path.join(dir_path, 'assets/admin/split_scoreboard_attr.html')).read())
ctfd_1   |   File "/opt/CTFd/CTFd/utils/plugins/__init__.py", line 41, in override_template
ctfd_1   |     app.overridden_templates[template] = html
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
ctfd_1   |     return getattr(self._get_current_object(), name)
ctfd_1   | AttributeError: 'CTFdFlask' object has no attribute 'overridden_templates'
ctfd-321_ctfd_1 exited with code 1
```

May i know which version of CTFd this work perfectly on ?

**Comment by durkinza** [comment]
If you're pulling the latest commit of this plugin, it should work on the latest ctfd version ([d0c92073](https://github.com/CTFd/CTFd/commit/d0c92073c33df2339bcf1a931a95b417f598f634))

**Comment by durkinza** [comment]
Please note that I've added changes to this commit since this issue has been created. however, I haven't touched the override_template function call. Which appears to be where this issue lies.

The function override_template is provided by ctfd's plugin implementations.
[here](https://github.com/CTFd/CTFd/blob/master/CTFd/utils/plugins/__init__.py#L40)

What version of CTFd are you wanting to run this plugin for? 
I may be able to find a previous commit of this plugin that works for your version.

**Comment by minhnq1618** [comment]
Hello, thank you for your help. I wanted it to run on CTFd 3.2.1
I just tested and it run perfectly on CTFd 3.3.0
I think this would be ok for me :D

**Comment by durkinza** [comment]
Awesome, glad it works!
I'll be pushing up one more commit tonight to fix some minor bugs. 

For older versions of CTFd you'll need the [CTFd_Team_Atttributes](https://github.com/durkinza/CTFd_Team_Attributes) plugin. Since that wasn't built into the platform at the time.

**Comment by minhnq1618** [comment]
Cool, thank you for your help :+1:
